# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='cEstatus',
            new_name='cestatus',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='cObservaciones',
            new_name='cobservaciones',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='id_univeridad',
            new_name='id_universidad',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='id_constulta',
            new_name='id_consulta',
        ),
    ]
